openapi: 3.0.3
info:
  title: exo1
  version: "1.0.0"

paths:
  /ping:
    get:
      summary: Pour jouer au ping pong
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
