openapi: 3.0.3
info:
  title: exo3
  version: "1.0.0"

paths:
  /tasks:
    get:
      summary: Retourne la liste des tâches
      responses:
        "200":
          description: Liste des tâches
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    post:
      summary: Crée une liste de nouvelles tâches
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Liste des nouvelles tâches créées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    delete:
      summary: Supprime une liste de tâches via leurs identifiants
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                example: 1
      responses:
        "200":
          description: Liste des tâches supprimées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

  /tasks/{id}:
    get:
      summary: Retourne une tâche par son ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tâche retrouvée
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Task not found

    delete:
      summary: Supprime une tâche par son ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tâche supprimée
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Tâche non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Task not found

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Faire les TD API
        completed:
          type: boolean
          example: true
          