openapi: 3.0.3
info:
  title: exo4 
  version: "1.0.0"

paths:
  /products:
    get:
      summary: Recherche de produits
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/QParam'
      responses:
        '200':
          description: Liste des produits
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                plusieursProduits:
                  summary: Exemple avec plusieurs produits
                  value:
                    - name: "Lait"
                      expiration_datetime: "2025-09-01T12:00:00Z"
                      price: 1.5
                    - name: "Pain"
                      expiration_datetime: "2025-09-03T18:30:00Z"
                      price: 0.9
                listeVide:
                  summary: Exemple avec une liste vide
                  value: []

components:
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
          example: "Lait"
        expiration_datetime:
          type: string
          format: date-time
          example: "2025-09-01T12:00:00Z"
        price:
          type: number
          format: float
          example: 1.5

  parameters:
    LimitParam:
      name: limit
      in: query
      description: Nombre maximum d’éléments à retourner
      required: false
      schema:
        type: integer
        example: 10
    QParam:
      name: q
      in: query
      description: Terme de recherche
      required: false
      schema:
        type: string
        example: "pain"
